// Generated by Wrangler by running `wrangler types`

interface Env {
	YATCC: KVNamespace;
	BOT_INFO: {"id":7618804505,"is_bot":true,"first_name":"yet_another_chat_bot","username":"yatccbot","can_join_groups":true,"can_read_all_group_messages":false,"supports_inline_queries":false,"can_connect_to_business":false,"has_main_web_app":false};
	BOT_TOKEN: string;
	secret_token: string;
	AI: Ai;
}
